name: Version Bump Test

on:
  push:

jobs:
  bump:
    name: Get Bumped Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Get current package version
        id: pkg
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Determine Version Bump Action
        id: version
        uses: PenPow/determine-version-bump-action@2.0
        with:
            currentVersion: ${{ steps.pkg.outputs.current-version }}

      - name: Log Output
        run: |
          echo Bumped: ${{ steps.version.outputs.bumpedVersion }}
          echo Change: ${{ steps.version.outputs.versionBump }}
        shell: bash
        
